package network;



public enum Endpoint {
    GET_TASKS, GET_TASK, GET_EPICS, GET_EPIC,GET_EPIC_SUBTASKS,GET_SUBTASKS, GET_SUBTASK, POST_TASK, POST_EPIC, POST_SUBTASK, DELETE_TASK, DELETE_EPIC, DELETE_SUBTASK, HISTORY, PRIORITIZED,UNKNOWN

}